 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dashboards", type: :request do
  # Dashboard. As you add validations to Dashboard, be sure to
  # adjust the attributes here as well.
  let(:user) { create(:user) }

  let(:valid_attributes) {
    {title: "First Dashboard", content: "Just some random content", user: user}
  }

  let(:invalid_attributes) {
    {title: "F", content: 12345}
  }

  before do
    sign_in(user)
  end

  describe "GET /index" do
    it "renders a successful response" do
      Dashboard.create! valid_attributes
      get dashboards_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dashboard = Dashboard.create! valid_attributes
      get dashboard_url(dashboard)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dashboard_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      dashboard = Dashboard.create! valid_attributes
      get edit_dashboard_url(dashboard)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Dashboard" do
        expect {
          post dashboards_url, params: { dashboard: valid_attributes }
        }.to change(Dashboard, :count).by(1)
      end

      it "redirects to the created dashboard" do
        post dashboards_url, params: { dashboard: valid_attributes }
        expect(response).to redirect_to(dashboard_url(Dashboard.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Dashboard" do
        expect {
          post dashboards_url, params: { dashboard: invalid_attributes }
        }.to change(Dashboard, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dashboards_url, params: { dashboard: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {title: "Second Dashboard", content: "Just some random content"}
      }

      it "updates the requested dashboard" do
        dashboard = Dashboard.create! valid_attributes
        patch dashboard_url(dashboard), params: { dashboard: new_attributes }
        dashboard.reload
        expect(dashboard.title).to eq new_attributes[:title]
      end

      it "redirects to the dashboard" do
        dashboard = Dashboard.create! valid_attributes
        patch dashboard_url(dashboard), params: { dashboard: new_attributes }
        dashboard.reload
        expect(response).to redirect_to(dashboard_url(dashboard))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        dashboard = Dashboard.create! valid_attributes
        patch dashboard_url(dashboard), params: { dashboard: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update-positions" do
    let(:user){ create(:user) }
    let!(:dashboard1) { create(:dashboard, position: 1, user: user) }
    let!(:dashboard2) { create(:dashboard, position: 2, user: user) }
    let!(:dashboard3) { create(:dashboard, position: 3, user: user) }
    let(:current_dashboards_order) { user.dashboards.pluck(:id).map(&:to_s) }
    
    context "with valid request params" do
      let(:new_dashboards_order) { ["1", "3", "2"] }

      it "updates the users dashboards positions" do
        headers = { "Accept": "application/json", "X-Requested-With": "XMLHttpRequest" }
        
        expect { 
          patch update_dashboard_positions_url, params: { dashboards_order: new_dashboards_order }, headers: headers
        }.to change { 
          user.dashboards.pluck(:id).map(&:to_s)
        }.from(current_dashboards_order).to(new_dashboards_order)

        expect(response.content_type).to eq("application/json")
        expect(response).to have_http_status(:ok)
      end
    end

    context "with invalid request params" do
      let(:new_dashboards_order) { ["foo", "bar", "baz"] }

      it "doesnt update the users dashboard position" do
        headers = { "Accept": "application/json", "X-Requested-With": "XMLHttpRequest" }
        
        expect { 
          patch update_dashboard_positions_url, params: { dashboards: new_dashboards_order }, headers: headers
        }.not_to change { 
          user.dashboards.pluck(:id).map(&:to_s)
        }.from(current_dashboards_order)

        expect(response.content_type).to eq("application/json")
        expect(response).to have_http_status(:not_found)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dashboard" do
      dashboard = Dashboard.create! valid_attributes
      expect {
        delete dashboard_url(dashboard)
      }.to change(Dashboard, :count).by(-1)
    end

    it "redirects to the dashboards list" do
      dashboard = Dashboard.create! valid_attributes
      delete dashboard_url(dashboard)
      expect(response).to redirect_to(dashboards_url)
    end
  end
end
